---
layout: post
num: 28
title: Exercise 28
chapter: Chapter 12
description: >
  (1) Modify Exercise 4 so that the custom exception class inherits from RuntimeException, and show that the compiler allows you to leave out the try block.
---



```java


package com.ciaoshen.thinkinjava.chapter12;

public class Exercise28 {
    public static class Exercise28Exception extends RuntimeException {
        private static final long serialVersionUID = 0l;
        private String message = "NULL";
        public Exercise28Exception(){
            super();
        }
        public Exercise28Exception(String msg) {
            message = msg;
        }
        public void showMessage() {
            System.out.println(message);
        }
    }
    public static void main(String[] args) {
        String justAMessage = "I am the message of Exercise4Exception!";
        throw new Exercise28Exception(justAMessage);
    }
}


```



